### ISSUE TITLE
autopb: Host creation date invalid

### ISSUE THREAD

**Issue by avluis** [hweidner/check-mk-goodies#1]
Good day! Lovely set of goodies.

When making use of autopb, the creation date defaults to a value that checkmk is unable to modify and errors out when updating the host.
![image](https://github.com/hweidner/check-mk-goodies/assets/875593/d7b2750c-0e44-4e15-ad33-24739710e538)

Error is "The value for year must be between 1970 and 2038"
![image](https://github.com/hweidner/check-mk-goodies/assets/875593/c55a5be8-accd-40c8-b986-fb3e921db654)

I've gotten around this by editing the following to have a value different than the default of `0.0` for `'created_at'`:

Excerpt:
https://github.com/hweidner/check-mk-goodies/blob/e941e85e012dc5bf7887d3766dee489b620280bc/autopb/autopb#L179-L185

Changes:
```perl
180 # Host attributes (needed for WATO)
181 host_attributes.update({
182 [% FOREACH host IN pbhosts -%]
183 #  '[% host.key %]': {'meta_data': {'created_at': 0.0, 'created_by': 'cmkadmin', 'updated_at': 0.0},
184 #                     'parents': [ '[% host.value.join("', '") %]' ]},
185   '[% host.key %]': {'meta_data': {'created_at': '1970-01-01T00:00:00', 'created_by': 'cmkadmin', 'updated_at': 0.0},
186                      'parents': [ '[% host.value.join("', '") %]' ]},
187 [% END -%]
188 })
```

I'm certain there is a better way, one that checkmk likes as I then see the following when a host is created:
![image](https://github.com/hweidner/check-mk-goodies/assets/875593/eee57e0f-baa5-444a-b019-fdfe1b3e008f)
But with that said, checkmk does not error out when making changes, instead it updates the value itself to be valid:
![image](https://github.com/hweidner/check-mk-goodies/assets/875593/c75da58b-8e87-42ab-9f54-024cfc477ad4)

**Comment by hweidner** [comment]
Which version of Checkmk are you using?
 
I have verified that on current 2.3 and 2.2 versions, the creation and update timestamp is stored as the Unix epoch, e.g. the number of seconds since 1970-01-01. However, it could be related to your time zone. Here in CET time zone, 0.0 is interpreted as 1970-01-01 01:00:00, and Checkmk does not complain.

Can you test replacing the 0.0 by a higher value, e.g. 1704067200.0, in both the created_at and updated_at fields? This should represent 2024-01-01 00:00 UTC, or 2023-31-12 in western time zones.

By the way, when you update the host, you should also move it to another folder, because all hosts in the autopb folder are regularly being rewritten.

**Comment by avluis** [comment]
Appreciate all the details in your response.
Currently running latest Checkmk 2.2. The container it is running in is setup for America/New_York (currently EST); will be testing the suggested value on those fields promptly.

And yes, I made use of that 'feature' as well to validate piggyback data and I have a few ideas for the autopb for those that run a docker swarm (where the containers change instance names when re-created).

**Comment by avluis** [comment]
Quick correction:
```bash
OMD[mysite]:~$ date
Fri Jun  7 10:52:24 EDT 2024
```
With the suggested changes I certainly see a valid date input:
![image](https://github.com/hweidner/check-mk-goodies/assets/875593/bdfb9271-ced3-4277-b289-e9ac649b2001)
